### PR TITLE
Add a widget for searches

### LINKED ISSUE #62: Widget/fast action for search
It would be very useful to have a widget or a fast action to search in all the notes.

### PR DESCRIPTION
**Pull request by MackieLoeffel**
Fixes #62.

Features:
- can select a search
- button for adding a new note
- autoupdates every minute
- updates on most of the common actions (saving, marking as done and some other ones)
- mark as done button for TODO items

Missing:
- [x] preview image
- [x] tests

There are some points, which are not ideal, maybe you have an idea, @nevenz, how these can be solved:
- AppWidgets don't support themes, so I had to copy a lot of the information from the default theme
- I had to copy quite a bit of code from the HeadListViewAdapter, because I could not use it directly. But I also refactored it a little bit and extracted at least the title generation.

### CODE REVIEW

**Comment by mkaito** [comment]
I was going to open an issue and request this. I'm glad to see I wasn't the first to have this idea!

Do I understand this correctly in that this creates a widget that displays the results of a search? It's not just a button that opens a search in orgzly?

I'm trying to switch from todoist to orgzly and this is something I miss. I'm the kind of person that needs to have their to-do list up in their face, lest I just forget to check my to-do app!

**Comment by MackieLoeffel** [comment]
Yes, it is a widget, which displays the results of a search. It looks like this: (you can also make it bigger, this is just the image for the preview)
list_widget_preview

**Comment by mkaito** [comment]
Oh my god, that's exactly what I need. Where do I buy you a beer?

**Comment by MackieLoeffel** [comment]
Glad to hear, that you like it.

**Comment by tkamat** [comment]
Omg this is amazing! You are truly amazing!

**Comment by nevenz** [comment]
Thanks for working on this.

I'll check it out. I did a quick try yesterday and started getting these:

```
04-30 13:22:07.851 3555-3555/com.orgzly D/com.orgzly.android.provider.Provider: 1#main: onCreate
04-30 13:22:07.852 3555-3555/com.orgzly D/com.orgzly.android.provider.Database: 1#main: <init>: orgzly.db 138
04-30 13:22:07.852 3555-3555/com.orgzly I/InstantRun: starting instant run server: is main process
04-30 13:22:07.856 3555-3555/com.orgzly D/com.orgzly.android.widgets.ListWidgetService: 1#main: onGetViewFactory: onGetViewFactory
04-30 13:22:07.869 3555-3568/com.orgzly D/com.orgzly.android.provider.Provider: 151#Binder:3555_2: query: content://com.orgzly/notes/queried null null null book_name, COALESCE(priority, 'B'), is_visible
04-30 13:22:07.874 3555-3568/com.orgzly D/com.orgzly.android.provider.Provider: 151#Binder:3555_2: queryNotesSearchQueried: SELECT * FROM notes_view WHERE (is_cut = 0 AND level > 0) ORDER BY book_name, COALESCE(priority, 'B'), is_visible []
04-30 13:22:07.874 3555-3568/com.orgzly D/com.orgzly.android.provider.Provider: 151#Binder:3555_2: query: Cursor count: 36 for null null null
04-30 13:22:07.876 3555-3568/com.orgzly D/com.orgzly.android.widgets.ListWidgetViewsFactory: 151#Binder:3555_2: getViewAt: getViewAt 0
04-30 13:22:07.882 3555-3568/com.orgzly E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 36 rows, 36 columns.
04-30 13:22:07.882 3555-3568/com.orgzly E/AndroidRuntime: FATAL EXCEPTION: Binder:3555_2
                                                          Process: com.orgzly, PID: 3555
                                                          java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                              at android.database.CursorWindow.nativeGetString(Native Method)
                                                              at android.database.CursorWindow.getString(CursorWindow.java:438)
                                                              at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                              at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                              at com.orgzly.android.provider.clients.NotesClient.fromCursor(NotesClient.java:166)
                                                              at com.orgzly.android.widgets.ListWidgetViewsFactory.getViewAt(ListWidgetViewsFactory.java:85)
                                                              at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getViewAt(RemoteViewsService.java:164)
                                                              at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:85)
                                                              at android.os.Binder.execTransact(Binder.java:565)
```

after creating a widget. Even when opening the app and the notebook.

I can't reproduce it again today, which is weird.  I'll keep an eye on that while going through the code.

**Comment by MackieLoeffel** [comment]
@nevenz, I thought a little about the tests, but since most of the changes are layout changes and since you can't test clicking on a widget, I don't know, what would be a good thing to test. Is there anything, for which you would like tests?

**Comment by nevenz** [comment]
> @nevenz, I thought a little about the tests, but since most of the changes are layout changes and since you can't test clicking on a widget, I don't know, what would be a good thing to test. Is there anything, for which you would like tests?

Maybe something a la ShareActivityTest would be possible for start?

**Comment by MackieLoeffel** [comment]
Hm, I haven't seen this stacktrace during my testing, but I can take a look, whether I find something, which could cause it.

I will take a look at [UI Automator](https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html) for testing the widget, since testing a widget with espresso is not possible.

**Comment by psamim** [comment]
This is great! Thanks. 👍

**Comment by nevenz** [comment]
Sorry for the delay, was mostly AFK-ish last week, so I was postponing this one.

I'll just dump my notes below. Some are minor nit-picking stuff, some less so. Kinda ordered by priority. ("Design" is last as I'll be probably tweaking some of those items no matter what in the end.)

### Crash
- After widget is created
- After clicking new note, entering title, then saving
- After opening app and entering notebook

Can't reproduce it again, it only happend the very first time.

```
04-30 13:22:07.851 3555-3555/com.orgzly D/com.orgzly.android.provider.Provider: 1#main: onCreate
04-30 13:22:07.852 3555-3555/com.orgzly D/com.orgzly.android.provider.Database: 1#main: <init>: orgzly.db 138
04-30 13:22:07.852 3555-3555/com.orgzly I/InstantRun: starting instant run server: is main process
04-30 13:22:07.856 3555-3555/com.orgzly D/com.orgzly.android.widgets.ListWidgetService: 1#main: onGetViewFactory: onGetViewFactory
04-30 13:22:07.869 3555-3568/com.orgzly D/com.orgzly.android.provider.Provider: 151#Binder:3555_2: query: content://com.orgzly/notes/queried null null null book_name, COALESCE(priority, 'B'), is_visible
04-30 13:22:07.874 3555-3568/com.orgzly D/com.orgzly.android.provider.Provider: 151#Binder:3555_2: queryNotesSearchQueried: SELECT * FROM notes_view WHERE (is_cut = 0 AND level > 0) ORDER BY book_name, COALESCE(priority, 'B'), is_visible []
04-30 13:22:07.874 3555-3568/com.orgzly D/com.orgzly.android.provider.Provider: 151#Binder:3555_2: query: Cursor count: 36 for null null null
04-30 13:22:07.876 3555-3568/com.orgzly D/com.orgzly.android.widgets.ListWidgetViewsFactory: 151#Binder:3555_2: getViewAt: getViewAt 0
04-30 13:22:07.882 3555-3568/com.orgzly E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 36 rows, 36 columns.
04-30 13:22:07.882 3555-3568/com.orgzly E/AndroidRuntime: FATAL EXCEPTION: Binder:3555_2
                                                          Process: com.orgzly, PID: 3555
                                                          java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                              at android.database.CursorWindow.nativeGetString(Native Method)
                                                              at android.database.CursorWindow.getString(CursorWindow.java:438)
                                                              at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                              at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                              at com.orgzly.android.provider.clients.NotesClient.fromCursor(NotesClient.java:166)
                                                              at com.orgzly.android.widgets.ListWidgetViewsFactory.getViewAt(ListWidgetViewsFactory.java:85)
                                                              at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getViewAt(RemoteViewsService.java:164)
                                                              at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:85)
                                                              at android.os.Binder.execTransact(Binder.java:565)
```
###  Why alarm, why not always `updateListContents`
In few more places, like syncing notebook for example (same as for reminders).
### If alarms are needed use `evernote/android-job`
For consistency, used already for reminders.
### "Problem loading widget" (API 16 emulator)
### Widgets not grouped by app in widget list (older APIs)
- Rename "Notebook" to "Orgzly notebook"
- Rename "Search" to "Orgzly search"
### Calling methods directly from app
Is that ok (for updating due to changes), broadcasting feels cleaner.
### "Select a filter" displays all notes
Confusing at start, implies everything is already set up.
### Hard-coded `TitleAttributes` values in code
### Using style (font sizes and colors in xml)
If not possible, perhaps set values programmatically (if worth at all).
### Preference name and key value
```
$ cat com.orgzly/shared_prefs/com.orgzly.action.ACTION_UPDATE_LIST_WIDGET.xml 
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="Filter9" value="1" />
</map>
```
###  Reusing `HeadsListViewAdapter` code
Maybe rename `TitleGenerator` to `HeadItemGenerator` and include planning times, though probably not worth it if `RemoteViews` has to be used.
### Do we want checkmark-equivalent for done items (undone)?
### Value of `PREFERENCES_ID`
Not an action, rename to avoid confusion.
### Move `com.orgzly.action.*` to `AppIntent` and rename to `com.orgzly.intent.action.*`
### Is cleanup in `onDeleted` needed (prefs, alarm)? Anywhere else?
### Design/layout
- Remove margin, add padding to item (left and right)
- Spinner and new-note bg colors - should be one - `action_bar_in_query`
- Spinner text looks weak (try bold)
- Titles are one-line, but planning times wrap
- Planning times are too big
- Icons vs text color
- Smaller checkmark, align (below new-note icon, next to title, not in the middle)
- `minHeight` too big for small devices

**Comment by MackieLoeffel** [comment]
Thanks for the feedback. I fixed some of the points you mentioned, some other are a bit trickier to solve.

> ### Crash
It looks like it crashed on this line in NotesClient.java:
```
String inheritedTags = Cursor.getString( cursor.getColumnIndex( ProviderContract.Notes.QueryParam.INHERITED_TAGS));
```
The log looks like the column INHERITED_TAGS was not found in the database. I couldn't find, how database migrations are implemented, but maybe the code executed, before the migration happened, which added INHERITED_TAGS? Maybe due to InstantRun? I'm just guessing, but it doesn't seem connected to the widget, because the crash is in code, that wasn't changed and, as you can see in the log, the cursor was correctly initialized before use.

> ### Why alarm, why not always updateListContents
I added updateListContents to all places in the clients, which update the relevant note state. The alarm is still needed, because the result of the search can change without a change in the database (e.g. when the day changes). When you merge the reminder code, it would be possible to create a single method, which updates the reminders and the widgets and is called everytime, when the db changes.

> ### If alarms are needed use evernote/android-job
Should I wait until you merge the reminders to change this library? Or should copy the relevant code from the reminder branch?

> ### "Problem loading widget" (API 16 emulator)
I can't reproduce this. When I try it, the widget works fine in an API 16 emulator.

> ### Widgets not grouped by app in widget list (older APIs)
Done

> ### Calling methods directly from app
I'm not an Android developer, so I prefer a simple method call to a broadcast, and it seems to work quite well. But if you don't like it, I can change it to a broadcast.

> ### "Select a filter" displays all notes
Changed, displays 'Select a filter by clicking on the title bar' now instead of all notes.

> ### Hard-coded TitleAttributes values in code
Is there a way to load a theme programmatically? `mContext.obtainStyledAttributes` does not work from a widget because a widget doesn't have a theme.

> ### Using style (font sizes and colors in xml)
I don't know, how to use the styles from the theme without being able to set the theme. Same question as above.

> ### Preference name and key value
Changed.

> ### Reusing HeadsListViewAdapter code
I thought about this quite a bit, but you have to use RemoteViews with widgets, so it is not possible to give the TextView to `HeadItemGenerator`. I thought about subclassing TextView and overriding setText to call remoteView.setTextViewText, but I don't know, whether this is worth it. What do you think?

> ### Do we want checkmark-equivalent for done items (undone)?
I don't like the idea of an undone button, since there is no undone button anywhere else. I thought about a next-state-button instead of the done button, but I prefer a done button for TODO notes and no button otherwise for my use case. So if you like the idea of a next-state-button, it should be a config option.

> ### Value of PREFERENCES_ID
Renamed.

> ### Move com.orgzly.action.* to AppIntent and rename to com.orgzly.intent.action.*
Done.

> ### Is cleanup in `onDeleted` needed (prefs, alarm)? Anywhere else?
I added cleanup for the preferences for a widget in `onDeleted`. The Alarm is cleaned up in `onDisabled`.

> ### Design/layout
I'm not a very good at making stuff look good, so I would leave these points to you. Feel free to change the looks however you see fit.  You can send me a PR against this branch, if you want.

**Comment by MackieLoeffel** [comment]
I hope, that I didn't miss anything. If there is anything else, don't hesitate to point it out.

**Comment by nevenz** [comment]
MackieLoeffel <notifications@github.com> writes:

>> ### Crash
> It looks like it crashed on this line in NotesClient.java:
> ```
> String inheritedTags = Cursor.getString( cursor.getColumnIndex( ProviderContract.Notes.QueryParam.INHERITED_TAGS));
> ```
> The log looks like the column INHERITED_TAGS was not found in the
> database. I couldn't find, how database migrations are implemented,
> but maybe the code executed, before the migration happened, which
> added INHERITED_TAGS? Maybe due to InstantRun?

Could be, though I've tried various combinations of installing and
running different apks etc. and still can't reproduce it.  Which I guess
is a good thing.

>> ### Why alarm, why not always updateListContents
> I added updateListContents to all places in the clients, which update
> the relevant note state. The alarm is still needed, because the result
> of the search can change without a change in the database (e.g. when
> the day changes).

Good point.

>> ### If alarms are needed use evernote/android-job
> Should I wait until you merge the reminders to change this library? Or
> should copy the relevant code from the reminder branch?

I'll see to merge both reminders and this, so we can start from there.

>> ### "Problem loading widget" (API 16 emulator)
> I can't reproduce this. When I try it, the widget works fine in an API
> 16 emulator.

I can't reproduce it either now.  I wonder if it's related to that
crash, some weird state I was in or something like that.

>> ### Calling methods directly from app
> I'm not an Android developer, so I prefer a simple method call to a
> broadcast, and it seems to work quite well. But if you don't like it,
> I can change it to a broadcast.

It's just that broadcasts are already used (onReceive itself), so mixing
the two doesn't feel right.  Making `updateAppWidgetLayouts` and
`updateListContents` private methods being the end result.

Also, I've been using broadcasts for reminders to notify about changes,
so there some potential for more code cleaning/merging later (as you
suggested).

>> ### Hard-coded TitleAttributes values in code
> Is there a way to load a theme programmatically?
> `mContext.obtainStyledAttributes` does not work from a widget because
> a widget doesn't have a theme.

Yes, check `setupTheme` in `CommonActivity`, used for changing color
scheme and font sizes.  Not sure if that would work.

>> ### Reusing HeadsListViewAdapter code
> I thought about this quite a bit, but you have to use RemoteViews with
> widgets, so it is not possible to give the TextView to
> `HeadItemGenerator`. I thought about subclassing TextView and
> overriding setText to call remoteView.setTextViewText, but I don't
> know, whether this is worth it. What do you think?

Don't think it is.

>> ### Do we want checkmark-equivalent for done items (undone)?
> I don't like the idea of an undone button, since there is no undone
> button anywhere else. I thought about a next-state-button instead of
> the done button, but I prefer a done button for TODO notes and no
> button otherwise for my use case. So if you like the idea of a
> next-state-button, it should be a config option.

I was thinking first TODO state, but that might be wrong in lot of
cases.  Nah, it's fine the way it is.  A lot of things could be
supported later (click and do something specific right from the widget),
but this is probably the most common action.

**Comment by nevenz** [comment]
One more thing - I think after opening note from the widget, when user is done with it, app should be closed, instead of staying in the notebook.

**Comment by nixmaniack** [comment]
@nevenz Can you push an alpha or a beta release with this feature to playstore or f-droid?

**Comment by nevenz** [comment]
I can push the latest code to Google Play's alpha channel if that would work for you? I'd also upload the APK to a GitHub release.

It would contain this and half-done reminders support, which could both use a lot of testing, so I think it's a good idea.

**Comment by nixmaniack** [comment]
@nevenz APK to Github release is fine with me. For a wider audience, may be alpha channel would make sense. I would like to test this feature.

**Comment by nevenz** [comment]
https://github.com/orgzly/orgzly-android/releases/tag/v1.5-alpha.1

Apparently you can't have both open beta and open alpha testing on Google Play, so I'm not going to change anything there for now.

**Comment by nixmaniack** [comment]
> https://github.com/orgzly/orgzly-android/releases/tag/v1.5-alpha.1

Thanks! 

> Apparently you can't have both open beta and open alpha testing on Google Play, so I'm not going to change anything there for now.

That's totally fine.

**Pull request merged**
