### PR TITLE
Generate SSH keys on the device

### PR DESCRIPTION
**Pull request by amberin**
N. B. This branch builds on top of #948.

Includes some minor general polish of Git-related code.

### CODE REVIEW

**Comment by amberin** [comment]
Commit da79faf8ad18472540531cc968c9a86408433249 resolves #785. I forgot to mention that in the commit message.

**Comment by amberin** [comment]
To anyone trying to run this code: You also need to merge #916 into your build, otherwise Orgzly has insufficient permissions in external storage to create the Git workdir.

**Comment by Xanaxus** [comment]
So to get this working, we need to build our own package?

**Comment by wiktor-k** [comment]
@amberin Would you be so kind to share a debug build of Orgzly apk that you're using?

You've made numerous improvements to the app but from what I can see the review can take a little bit of time. Me (and I guess a couple of other folks) would be happy to... err... beta-test your changes :)

The git repo sync that's in stable is completely broken and following your issues / PRs it seems it will take some time to fix that.

Thanks for your work & time! :wave:

**Comment by amberin** [comment]
@wiktor-k wrote:

> @amberin Would you be so kind to share a debug build of Orgzly apk that you're using?

Sure. I just made a build off this branch https://github.com/amberin/orgzly-android/commits/faster-git-syncing and uploaded it to a site that I control: https://www.koloni.info/orgzly-fdroid-debug-amberin-738c3e5.apk

It's a build with all my latest changes which is working well for me. Be aware that I recently implemented deleting notebooks from the remote repository...

Obviously, I give no guarantees that this APK will not completely ruin your Org files or your phone. :)

I only have time to sit down with this a few times per year, so any bugs will not be fixed quickly. But it would be awesome if more people used the Git feature and could contribute to it.

I guess this might also interest @Xanaxus @tillmann @maikol-solis @mtekman.

**Comment by Xanaxus** [comment]
Hey so i did give it go just now and i got an error which says that the said packagee is invalid 

I am using an oppo reno 6 5g variant

**Comment by amberin** [comment]
> Hey so i did give it go just now and i got an error which says that the said packagee is invalid
> 
> I am using an oppo reno 6 5g variant

@Xanaxus Sorry, I uploaded the wrong APK. The link should work now. (It works for a friend of mine.)

**Comment by amberin** [comment]
Closing this in favor of #1037.

**Pull request closed without merging**
