### PR TITLE
Agenda feature, fixes #55

### LINKED ISSUE #55: Support for agenda view
Is there any agenda view functionality in Orgzly equivalent to 'C-c a a' in Org-mode? 
To get the agenda of the coming week with a daily view, it seems that creating a search with:
`.i.done s.1w g.day`   
or     
`.i.done a.7d`
might be different ways to provide an agenda view. However, agenda (a) and grouping (g) seems to be not implemented. Is there a plan to support agenda views? and is there anyone working on this? If not, is extending the search with (a) and (g) the way to go?

I would be interested in working on this!

### PR DESCRIPTION
**Pull request by pxsalehi**
Agenda feature for Orgzly!

### CODE REVIEW

**Comment by pxsalehi** [comment]
Sorry for the reoprn and name change. I was trying to make it attach/refer to the issue! Doesn't seem to work though!

**Comment by neeasade** [comment]
link for the lazy https://github.com/orgzly/orgzly-android/issues/55

**Comment by nevenz** [comment]
Sorry for the delay. I started using it, but I really miss filtering. I have some old notes in the files which are not part of agenda and they all show up in Orgzly now.

How hard would it be to make search query editable? Like in saved searches?

That would bring us back to the idea of just extending saved search though, but that can be part of code cleaning later, if it would require too many changes now.

**Comment by pxsalehi** [comment]
I think adding search to agenda would make it more of a fancy saved search than an agenda, like you mentioned. Personally, I think allowing to select notebooks that are listed in the agenda (similar to `org-agenda-files`) or allowing the user to add additional filters to the query used by the agenda would be more like an agenda and more familiar to an Orgmode user.

Would it be possible to try to merge the existing agenda and try to modify it later (e.g. notebook selection or additional queries)? Unfortunately, I will not have time to work on this for a while!

**Comment by nevenz** [comment]
> I think adding search to agenda would make it more of a fancy saved search than an agenda, like you mentioned. Personally, I think allowing to select notebooks that are listed in the agenda (similar to org-agenda-files) or allowing the user to add additional filters to the query used by the agenda would be more like an agenda and more familiar to an Orgmode user.

It does boil down being the same thing.

> Would it be possible to try to merge the existing agenda and try to modify it later (e.g. notebook selection or additional queries)? Unfortunately, I will not have time to work on this for a while!

Yes, I do want to include it in the next version. Thanks!

**Comment by nevenz** [comment]
Can you please just rebase this, it would be great. Squashing commits too would be even better, but you don't have to. Thanks!

**Comment by nevenz** [comment]
> Can you please just rebase this

NVM, I did it.

**Comment by nevenz** [comment]
> Can you please just rebase this

I've tried just merging it, but the history looks hard to track. Let me know if you can do this and need help.

**Comment by nevenz** [comment]
After changing my mind few times on how to do this, this is now merged. 😄

**Comment by pxsalehi** [comment]
Thanks! Just out of curiosity, what was the problem with the history? Unsquashed commits? or was it because I merged with upstream rather than rebase? And second question, id I have merged with upstream, what is the point of rebasing again or how would that work (without undoing the merge)?

**Comment by nevenz** [comment]
> Just out of curiosity, what was the problem with the history? Unsquashed commits? or was it because I merged with upstream rather than rebase?

Not really a problem, just a messy `log --graph`, nothing important. Yeah, rebasing instead of merging would have avoided that.

> And second question, id I have merged with upstream, what is the point of rebasing again or how would that work (without undoing the merge)?

I did end up doing a rebase. Check out the current `git log --oneline --graph` for example. I don't see why merging master from time to time would be an issue for rebase. It just applies other commits one by one. I think - I'm no git expert and don't have much experience with rebasing.

**Pull request merged**
