### PR TITLE
"Or" Searches

### PR DESCRIPTION
**Pull request by Sodel-the-Vociferous**
This implements the "or" operator in searches.

Now, searches like `tn.tag1 b.book1 or tn.tag2` are possible.

### CODE REVIEW

**Comment by Sodel-the-Vociferous** [comment]
Should provide a solution for #124.

**Comment by IvanMalison** [comment]
Whats the status of this?

**Comment by nevenz** [comment]
Ivan Malison <notifications@github.com> writes:

> Whats the status of this?

It's in my queue.

**Comment by nevenz** [comment]
Thanks!

This is likely to be rewritten soon though, there has been some talk about it in #149. We probably shouldn't expose `currentGroup` like that, although I do realise re-writing tests could be tricky.

I also feel like we need to support grouping (and explicit `and` operator) together with it, to avoid questions, requests and possible confusion -- for example, first thing I did when I tried this is expecting `i.todo or i.next i.work` to be (`i.todo or i.next) and i.work`.

( I know I was suggesting `and` to have precedence in the past, but that was with *explicit* operator specified. Though I think the logic is still fine as it is now. )

**Comment by Sodel-the-Vociferous** [comment]
Yup, I knew this was all likely to be rewritten. Otherwise I'd never expose currentGroup like that -- I agree it's a "code smell". 
(And, you're right that I kind of violate the principle of least astonishment with grouping. But until we require that either "and" or "or" be explicitly added between all query terms, one of them has to take precedence. And I definitely don't want to break backwards compatibility! Anyway, I'll continue in #149 if I get any decent ideas.)

**Pull request merged**
