### PR TITLE
Notes count in notebooks list

### PR DESCRIPTION
**Pull request by fresheed**
This is the feature discussed in #117 . I've implemented detail view which displays amount of notes (without taking into accout their hierarchy). To do this, I've added corresponding subquery to book view. Also some refactoring of BooksFragment was performed.
I'm not sure where test for this should be placed. For this moment it belongs to BooksTest.

### CODE REVIEW

**Comment by fresheed** [comment]
Rebased previous commits to latest master state

**Comment by nevenz** [comment]
We probably want this added to Settings's "Notebook -> Details", like other details, so it can be toggled.

And if you can rename variables to use camel case it would be great.

Thanks! (And sorry for very late reply.)

**Comment by nevenz** [comment]
Oh and one issue - cut notes and root note are also counted.

Check `DatabaseUtils.WHERE_EXISTING_NOTES`.

**Comment by fresheed** [comment]
Done

**Comment by nevenz** [comment]
Few changes I made:

* Removed one DB_VER
* Moved line after modification time, to keep last-action last (so it's easy to spot, as it's important) 
* Icon changed (the previous one was too strong compared to others)
* Extracted strings and used plurals (we had "Contains 1 notes")

Thanks again!

**Comment by fresheed** [comment]
Thank you for great efforts on making org portable!

**Pull request merged**
