### PR TITLE
Git sync multiple improvements

### PR DESCRIPTION
**Pull request by amberin**
This is one PR gathering all of my unmerged Git-related changes. I will close the others.

I am opening this because I now have some more work to share, and I have done some rebasing of changes in the other unmerged branches.

As before, anyone wanting to run this code must also merge #916, as local storage permissions are broken without it.

I will happily split this PR into smaller pieces, if needed, once someone gets around to reviewing it.

### CODE REVIEW

**Comment by Xanaxus** [comment]
Hey, I tried your apk whic you graciously provided but I am able to generate a key but when i go to repo option to set up the git option. Upon touching it the application carshes

Devive: oppo reno 6 5g [Not rooted]

**Comment by amberin** [comment]
@Xanaxus Yeah, I get the same behavior now... I will take a look at it.

**Comment by amberin** [comment]
@Xanaxus I found the problem. New APK: https://koloni.info/orgzly-fdroid-debug-amberin-7f628ef2.apk

**Comment by amberin** [comment]
@Xanaxus I found the issue. New APK: https://koloni.info/orgzly-fdroid-debug-amberin-8e583282.apk

**Comment by Xanaxus** [comment]
Hey it works!!

**Comment by wiktor-k** [comment]
Indeed. Thank you so much @amberin :pray: I've changed application ID in my fork (so that one can run official Orgzly and yours) and also enabled GitHub actions in fork and the APK is built by GitHub: https://github.com/wiktor-k/orgzly-android/actions/runs/4466053393

(Currently the workflow file builds artifacts only for `master` and `release...` branches so I just pushed to my `master`).

Thanks again and have a great day! :wave: 

Edit: ugh, changing package name was not a good idea as it's hardcoded in the app in many places and the app crashes here and there :-/

**Comment by maikol-solis** [comment]
> @Xanaxus I found the issue. New APK: https://koloni.info/orgzly-fdroid-debug-amberin-8e583282.apk

This build definitely works. I'm running it right now without problems. 

Thank you so much!

**Comment by dariuskramer** [comment]
> @Xanaxus I found the issue. New APK: https://koloni.info/orgzly-fdroid-debug-amberin-8e583282.apk

Hi @Xanaxus. I've just installed your APK and I get an error when I want to add a Git repo:
> Failure while cloning: Failed resolution of: Ljavax/management/ReflectionExcepti...

The rest of the error message is truncated unfortunately :(

**Comment by Xanaxus** [comment]
> > @Xanaxus I found the issue. New APK: https://koloni.info/orgzly-fdroid-debug-amberin-8e583282.apk
> 
> Hi @Xanaxus. I've just installed your APK and I get an error when I want to add a Git repo:
> > Failure while cloning: Failed resolution of: Ljavax/management/ReflectionExcepti...
> 
> The rest of the error message is truncated unfortunately :(

Hey I just tried it and the apk still works though the main apk is yet to.... the error you mentioned is because u havvent added the ssh key to you git account

**Comment by colonelpanic8** [comment]
@amberin When was the last time we heard from @nevenz? I think it may be time for a fork?

**Comment by amberin** [comment]
> @amberin When was the last time we heard from @nevenz? I think it may be time for a fork?

All I know is that he made the last commits on master in Nov 2022.

I'm afraid I am too inexperienced and lack the time to maintain a fork of such a mature project. But I agree with you that a fork would be desirable if Nevenz does not reappear...

**Comment by Nojipiz** [comment]
I need this code merged now! :c
The idea if making a fork it's nice, with 100k+ downloads in playstore (an a bunch more in FOSS sites), i think is more than a side project of @nevenz .

**Comment by colonelpanic8** [comment]
> I need this code merged now! :c
> The idea if making a fork it's nice, with 100k+ downloads in playstore (an a bunch more in FOSS sites), i think is more than a side project of @nevenz .

I can't tell if you're saying you approve or don't of a fork.

I think it could be done in an unobtrusive way such that if @nevenz reemerges he can sort of take control again. It's just that at this point there's a ton of stuff outstanding that needs to be fixed.

**Comment by Nojipiz** [comment]
@colonelpanic8 
Isn't that the idea? 
And of course i support the idea of a fork.

Edit: Actually i think that make a fork just for publish "temporal" versions as github releases can be enough.

**Comment by Nojipiz** [comment]
Fast question, @amberin Have you tried the ssh key generation in a release build?

I got the error message: **Error while trying to generate the SSH key pair** Message:  "ia.m" after the biometric authentication.

I think it can happen because the minify/shrink or proguard config because i put the release config in the debug buldType and starts to show the error:

 **Error while trying to generate the SSH key pair** Message:  "org.apache.sshd.common.config.keys.KeyUtils"

**Comment by amberin** [comment]
> Fast question, @amberin Have you tried the ssh key generation in a release build?
> 
> I got the error message: **Error while trying to generate the SSH key pair** Message: "ia.m" after the biometric authentication.
> 
> I think it can happen because the minify/shrink or proguard config because i put the release config in the debug buldType and starts to show the error:
> 
> **Error while trying to generate the SSH key pair** Message: "org.apache.sshd.common.config.keys.KeyUtils"

@Nojipiz I have not. So you may have found a bug.

**Comment by colonelpanic8** [comment]
I can volunteer to be part of a committee that maintains a fork of orgzly and tries to merge and release some of the pull requests that are seen as most urgent.

What do people think about this?

Just going off of the contributor information that I didn't look at to closely, it seems like @amberin @pxsalehi @tulth @maikol-solis  and myself are probably in the best position to do something like this.

Obviously, none of us are going to know the codebase as well as @nevenz and I'm happy to relinquish any sort of control the moment he shows up.

anyway, I've created https://github.com/orgs/orgzly-community to enable this project.

Please let me know if you think I've left anyone obvious out, or if there is information that I'm not aware of about @nevenz status.

**Comment by colonelpanic8** [comment]
@amberin I started by merging this and #916

Is there anything else we should do to start. And is there anywhere we should try to publicize this?

**Comment by amberin** [comment]
> I can volunteer to be part of a committee that maintains a fork of orgzly and tries to merge and release some of the pull requests that are seen as most urgent.
> 
> What do people think about this?
> 
> Just going off of the contributor information that I didn't look at to closely, it seems like @amberin @pxsalehi @tulth @maikol-solis and myself are probably in the best position to do something like this.
> 
> Obviously, none of us are going to know the codebase as well as @nevenz and I'm happy to relinquish any sort of control the moment he shows up.
> 
> anyway, I've created https://github.com/orgs/orgzly-community to enable this project.
> 
> Please let me know if you think I've left anyone obvious out, or if there is information that I'm not aware of about @nevenz status.

Thank you @colonelpanic8, that sounds excellent to me. I am currently very pressed for time, myself, but I would be happy to join such a committee, and it seems there are a bunch of people willing to contribute code.

**Comment by colonelpanic8** [comment]
> bunch of people willing to contribute code.

yeah I mean, thats the thing, I'm also very pressed for time, but I think I can do a reasonably good job coordinating merges and making sure they are of a reasonable enough quality with some help from some other people, and I think its important that we keep the ball rolling before all enthusiasm dies out.

**Comment by amberin** [comment]
I will create some issues in the new repo about stuff that's been bothering me, just to get the ball rolling. 😀🚀

**Comment by Itrekr** [comment]
Sorry for posting here as I don't know what the least intrusive way would be to ask this: how do I compile the new APK? The generate APK button in the actions page produces the error: "The logs for this run have expired and are no longer available."

**Comment by amberin** [comment]
> @amberin I started by merging this and #916
> 
> Is there anything else we should do to start. And is there anywhere we should try to publicize this?

I suppose one of the first tasks is to figure out an automated way to provide an APK built from the new repo's main branch.

**Comment by colonelpanic8** [comment]
> I suppose one of the first tasks is to figure out an automated way to provide an APK built from the new repo's main branch.

yeah, for sure!

**Comment by wiktor-k** [comment]
> I suppose one of the first tasks is to figure out an automated way to provide an APK built from the new repo's main branch.

Actually the repo already contains workflow files needed to produce that file. I think I had to press some buttons in the repo config to enable actions and they worked.

Example from my ancient repo: https://github.com/wiktor-k/orgzly-android/actions

**Pull request closed without merging**
