### PR TITLE
Make a proper Readme

### PR DESCRIPTION
**Pull request by licaon-kter**
with F-Droid link and all

### CODE REVIEW

**Comment by nevenz** [comment]
Can we:
* Use `README.org` instead of Markdown, it's just feels weird not too. :)
* Fix first bullet to say "Store notebooks... and keep them ..."
* Put Google Play badge before F-Droid. I prefer users using the app on Google Play if the can.

Thanks!

**Comment by gdt** [comment]
It seems strange to prefer google play, since org is part of the Free Software world and I would expect org things to have a bias to Free network services over proprietary services.

**Comment by nevenz** [comment]
I (as a developer) prefer Google Play for the stats and more importantly crash reports.

**Comment by licaon-kter** [comment]
> Use README.org instead of Markdown, it's just feels weird not too. :)

Feel free to edit it, I don't know how (org sintax). ;)
Be sure to test it though, the previous one had the `#+html:` thing that was useless as a webpage (eg. use ForkHub to read that file). Markdown is kinda standard around GitHub.

> Fix first bullet to say "Store notebooks... and keep them ..."

Right, sorry.

> Put Google Play badge before F-Droid. I prefer users using the app on Google Play if the can.

Done, although you realise F-Droid users won't start using the Google Play store one or the other way around based on logo position, right? :)

**Comment by nevenz** [comment]
`#+html:` should work (I had to use that to make image smaller, as `#+ATTR_HTML` doesn't seem to be supported by GitHub), though I agree Markdown makes that easier.

If someone wants to play with `README.org` in the future, great. :)

Thanks again!

**Pull request merged**
