### PR TITLE
Add Persian translation

### PR DESCRIPTION
**Pull request by mamins1376**

### CODE REVIEW

**Comment by nevenz** [comment]
Great, thanks!

Can you just please remove those with `translatable="false"`, as this:

```
./gradlew build
```

is failing:

```
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:58: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="bullet" translatable="false">•</string>
                          ~~~~~~~~~~~~~~~~~~~~
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:59: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="bullet_with_children_folded" translatable="false">+</string>
                                               ~~~~~~~~~~~~~~~~~~~~
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:60: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="bullet_with_children_unfolded" translatable="false">–</string>
                                                 ~~~~~~~~~~~~~~~~~~~~
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:103: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="synced_rook_revision_sample" translatable="false">42f97fe238</string>
                                               ~~~~~~~~~~~~~~~~~~~~
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:242: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="unfold_button_character" translatable="false">+</string>
                                           ~~~~~~~~~~~~~~~~~~~~
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:243: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="fold_button_character" translatable="false">–</string>
                                         ~~~~~~~~~~~~~~~~~~~~
/Users/neven/repo/orgzly/orgzly-android/app/src/main/res/values-fa/strings.xml:396: Error: Non-translatable resources should only be defined in the base values/ folder [ExtraTranslation]
    <string name="default_share_notebook" translatable="false">Inbox</string>
                                          ~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.).

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.

7 errors, 0 warnings
:app:lintVitalFdroidRelease FAILED

FAILURE: Build failed with an exception.
```

**Comment by mamins1376** [comment]
Mentioned lines are now removed.

**Comment by nevenz** [comment]
Cool, those errors are gone now.

There's one more issue (which I apparently missed the first time), regarding plurals:

```
The quantity 'one' matches more than one specific number in this locale (0, 1), but the message did not include a formatting argument (such as %d). This is usually an internationalization error.
```

That refers to `quantity="one"` in these 3:

```
    <plurals name="notes_deleted">
        <item quantity="one">یادداشت حذف شد</item>
        <item quantity="other"><b>%d</b> یادداشت حذف شد</item>
    </plurals>

    <plurals name="notes_cut">
        <item quantity="one">یادداشت بریده‌شد</item>
        <item quantity="other"><b>%d</b> یادداشت بریده‌شد</item>
    </plurals>

    <plurals name="notes_pasted">
        <item quantity="one">یادداشت چسبانده‌شد</item>
        <item quantity="other"><b>%d</b> یادداشت چسبانده‌شد</item>
    </plurals>
```

Does this make sense? Can `quantity="one"` translations refer to both 0 and 1, and can %d be squeezed in there? If not, I'll just disable that lint check.

**Comment by mamins1376** [comment]
We need another string for each operation to contain special translation (which would only matches 0, e.g. meaning "No notes were pasted").
Is this possible to provide a template or a reference to such? I'll fix this ASAP.

**Comment by nevenz** [comment]
There is also `zero` supported (https://developer.android.com/guide/topics/resources/string-resource.html#Plurals). But even if I add it:

    <plurals name="notes_deleted">
        <item quantity="zero">هیچ یادداشتی پاک نشد</item>
        <item quantity="one">یادداشت حذف شد</item>
        <item quantity="other"><b>%d</b> یادداشت حذف شد</item>
    </plurals>

it still complains about `%d` not being in the second item (`quantity="one"`).

(I used `no_notes_deleted` for the first item above. It can actually be moved there, though for some strings it needs to be separated, as it's also used separately.)

The only thing that works is when I put `%d` in item for `quantity="one"` somewhere:

```
    <plurals name="notes_deleted">
        <item quantity="one">یاداش%d ت حذف شد</item>
        <item quantity="other"><b>%d</b> یادداشت حذف شد</item>
    </plurals>
```

I'm sure above doesn't make sense, I randomly added `%d` in there. :)

**Comment by mamins1376** [comment]
It can take place at the beginning of the sentence, but however it is not needed and completely optional.
The build is ready to be tested again.

Unfotunately, I don't have an android setup for building and testing the changes. sorry for this :)

**Comment by nevenz** [comment]
Passes fine now, thanks!

**Pull request merged**
